version: '3.8'

services:
  frontend:
    build:
      context: ./react-dashboard
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./realtime-dashboard-backend
    ports:
      - "4000:4000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
